version: "3.7"

services:
  jobLoggerDb:
    image: mysql:5.7.27
    container_name: jobLogger
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jobLogger123
      MYSQL_DATABASE: log
      MYSQL_USER: jobLogger
      MYSQL_PASSWORD: jobLogger123
